version: '2'
services:
    whipround-app:
        image: whipround
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://whipround-mysql:3306/whipround?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    whipround-mysql:
        extends:
            file: mysql.yml
            service: whipround-mysql
